
dist: trusty

addons:
    apt:
        sources:
            - 'ubuntu-toolchain-r-test'
            - 'llvm-toolchain-trusty-5.0'
        packages:
            - gcc-7
            - g++-7



language: cpp

install:
    - export CC='gcc-7'; export CXX='g++-7'
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo apt-get autoremove llvm clang
    - sudo apt-get install llvm-5.0 llvm-5.0-dev
    - sudo rm -rf /usr/include/llvm
    - sudo rm -rf /usr/include/llvm-c
      #    - sudo rm /usr/local/clang-3.5.0/bin/llvm-config

script: make && make test

