
dist: trusty

addons:
    apt:
        sources:
            - 'ubuntu-toolchain-r-test'
            - 'george-edison55-precise-backports'
            - 'llvm-toolchain-trusty-4.0'

        packages:
            - gcc-4.9
            - g++-4.9

cache:
    - llvm-4.0
    - llvm-4.0-dev


language: cpp

install:
    - export CC='gcc-4.9'; export CXX='g++-4.9'
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo apt-get install clang-4.0
    - sudo apt-get install llvm-4.0
    - sudo apt-get install llvm-4.0-dev
    - ls /usr/include/llvm-4.0/llvm
    - mv /usr/include/llvm-4.0/llvm /usr/include/llvm

script: make

compiler:
  - gcc


