
addons:
    apt:
        sources:
            - 'ubuntu-toolchain-r-test'
            - 'george-edison55-precise-backports'
            - 'llvm-toolchain-precise-4.0'

        packages:
            - gcc-4.9
            - g++-4.9


language: cpp

install:
    - export CC='gcc-4.9'; export CXX='g++-4.9'

script: make

compiler:
  - gcc


