
addons:
    apt:
        sources:
            - 'ubuntu-toolchain-r-test'
            - 'george-edison55-precise-backports'
            - 'llvm-toolchain-trusty-4.0'

        packages:
            - gcc-4.9
            - g++-4.9
            - llvm-4.0.0
            - llvm-4.0.0-dev


language: cpp

install:
    - export CC='gcc-4.9'; export CXX='g++-4.9'

script: make

compiler:
  - gcc


