
dist: trusty

addons:
    apt:
        sources:
            - 'ubuntu-toolchain-r-test'
            - 'llvm-toolchain-trusty-4.0'
        packages:
            - gcc-6
            - g++-6



language: cpp

install:
    - export CC='gcc-6'; export CXX='g++-6'
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo apt-get install llvm-4.0
    - sudo apt-get install llvm-4.0-dev
    - sudo rm -rf /usr/include/llvm
    - sudo mv /usr/include/llvm-4.0/llvm /usr/include/
    - sudo rm -rf /usr/include/llvm-c
    - sudo mv /usr/include/llvm-c-4.0/llvm-c /usr/include/
    - sudo mv /usr/bin/llvm-config-4.0 /usr/bin/llvm-config
    - sudo cp -avr /usr/lib/llvm-4.0/lib/* /usr/lib

script: make

