language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  - sudo ./llvm.sh 10
  - export CC=clang-10
  - export CXX=clang-10
  - export clang=clang-10
  - export LLVM_SYS_100_PREFIX=/usr
