
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:xorg-edgers/ppa -y

  - sudo apt-get -qq update
  - sudo apt-get install -y gcc-6 clang-4.0 llvm-4.0 llvm-4.0-dev


language: cpp

script: make

compiler:
  - clang
  - gcc


