
cache:
    directories:
        - llvm-4.0.0
        - llvm-3.9.1

addons:
    apt:
        sources:
            - 'ubuntu-toolchain-r-test'
            - 'george-edison55-precise-backports'

        packages:
            - 'gcc-4.9'
            - 'g++-4.9'


language: cpp

install:
    - export CC='gcc-4.9'; export CXX='g++-4.9'

script: make

compiler:
  - gcc


