
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - wget http://apt.llvm.org/precise/llvm-toolchain-precise-4.0
  - dpkg -i llvm-toolchain-precise-4.0.deb
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -

  - sudo apt-get -qq update
  - sudo apt-get install -y gcc-6 clang-4.0 llvm-4.0 llvm-4.0-dev


language: cpp

script: make

compiler:
  - clang
  - gcc


