[package]
name = "ante"
version = "0.1.1"
authors = ["Jake Fecher <jfecher11@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.1.0", features = ["derive"] }
colored = "2.0.0"
mimalloc = { version = "0.1.19", default-features = false }
difference = "2.0.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm13-0"], optional = true }
dirs = "4.0.0"
cranelift = "0.81"
cranelift-module = "0.81"

[dev-dependencies]
goldentests = "1.1.0"

[build-dependencies]
dirs = "4.0.0"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
debug = true

[features]
llvm = ["inkwell"]