[package]
name = "ante"
version = "0.1.0"
authors = ["Jake Fecher <jfecher11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
colored = "1.9"
mimalloc = { version = "0.1.19", default-features = false }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
