baseURL = "https://jfecher.github.io/ante/public/"
languageCode = "en-us"
title = "Ante"

theme = "hyde"

pygmentsUseClassic = true
pygmentsUseClasses = true
pygmentsCodeFences = true

newContentEditor = "vim"

[params]
  description = "A systems programming language focused on providing extreme extensibility without compromising on speed or readability"

