comment_width = 100
condense_wildcard_suffixes = true
fn_args_layout = "Compressed"
format_code_in_doc_comments = true
format_macro_matchers = true
# imports_indent = "Visual"
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
