name: Rust

on:
  push:
    branches: [ master, ci-test ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    name: Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CONFIGURATION:
        -
        - release

    steps:
    - uses: actions/checkout@v2
    - name: Build LLVM
      run: |
        cargo install llvmenv
        llvmenv init
        llvmenv build-entry -G Makefile -j7 13.0.0
        llvmenv global 13.0.0
        export LLVM_SYS_130_PREFIX=$(llvmenv prefix)
    - name: Build Ante ${{matrix.CONFIGURATION}}
      run: cargo build --verbose ${{matrix.CONFIGURATION}}
    - name: Run tests
      run: cargo test --verbose ${{matrix.CONFIGURATION}}

  windows:
    name: Windows Build
    runs-on: windows-latest
    env:
      BUILD_PROJECT: llvm
      BUILD_MASTER: false
      LLVM_VERSION: 13.0.0

    strategy:
      fail-fast: false
      matrix:
        CRT:
        - msvcrt

        TARGET_CPU:
        - x86
        - amd64

        CONFIGURATION:
        - Debug
        - Release

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install
      shell: cmd
      run: |
          call %GITHUB_WORKSPACE%\.github\windows-ci\set-env.bat msvc15 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
          call %GITHUB_WORKSPACE%\.github\windows-ci\install.bat
          call %GITHUB_WORKSPACE%\.github\windows-ci\build.bat
          set LLVM_SYS_130_PREFIX=%WORKING_DIR%\llvm\build\
          echo "set LLVM_SYS_130_PREFIX=%LLVM_SYS_130_PREFIX%"
          ls %LLVM_SYS_130_PREFIX%

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose